version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
    build: .
    container_name: student-information-system
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=test
      - SERVER_PORT=8081
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA=debug
      - LOGGING_LEVEL_ROOT=error